Allow previewing products on mocked template
maykinmedia/sdg-invoervoorziening pull request #343
Opened 2022-01-05 16:59 UTC by dariomory

Fixes #22

_______

**Changes**

- Added KVK mock website for preview

2022-01-11 14:48 UTC, joeribekker requested changes
Looks good, small changes needed:

* [x] Change the title to "SDG invoervoorziening | Voorbeeld weergave"
* [x] If a field has no value, hide the field title/block entirely.
* [ ] Change the Preview link to a button, next to "Wijzigen" and call it "Voorbeeld weergeven".

![image](https://user-images.githubusercontent.com/96970/148963597-8a47c702-67b8-4305-8e25-96cfc9a9072f.png)

* [x] A. Change to: "Voorbeeld weergave"  (it's like a title)
* [x] B. Change to: "Terug naar de SDG-invoervoorziening" (make this a link that returns to the detail page of the SDG CMS)
* [x] C. Change to: "Hieronder staat een voorbeeld van de producttekst zoals deze zou kunnen worden weergeven door een website."
* [ ] D. Change to: "Laatst gewijzigd op {{ last_modified_date }}. {% if published %}Gepubliceerd op {{ published_date }}{% endif %}"  (pseudo code)
* [x] E. Remove this

![image](https://user-images.githubusercontent.com/96970/148964514-a99842d4-8019-49a3-b1f5-b628a55a293b.png)

* [x] Remove above footer elements

2022-01-14 16:06 UTC, dariomory commented
Some issues:

> Change the Preview link to a button, next to "Wijzigen" and call it "Voorbeeld weergeven".

It is possible to preview translations from two languages, putting this outside the box is only ideal if we are previewing a single language.

> B. Change to: "Terug naar de SDG-invoervoorziening" (make this a link that returns to the detail page of the SDG CMS)

Because the link opens in a new tab, this is slightly inconvenient (It can lead to two tabs open with the same page).

2022-01-18 10:33 UTC, joeribekker requested changes
* [ ] Change B so that the link closes the page
* [ ] Text for D is still incorrect

2022-01-18 12:17 UTC, joeribekker approved these changes

2022-01-18 12:17 UTC, merged