Feature/629 producten crud api
maykinmedia/sdg-invoervoorziening pull request #654
Opened 2022-06-17 14:15 UTC by bart-maykin

Fixes #629 

_______

**Changes**

Added update, create and delete call for the producten call

added tests for these api calls

added default catalogus to a organisation

2022-06-21 14:21 UTC, joeribekker requested changes

2022-06-21 14:21 UTC, joeribekker commented on src/sdg/api/serializers/producten.py
> +            for vertaling in vertalingen:
We always create all available languages, so iterate over TaalChoices, like done here: https://github.com/maykinmedia/sdg-invoervoorziening/pull/654/files#diff-4d8eb0ae426869d19f172e59b7f7d020e47859073f9edae8e288125d53896270R162

2022-06-21 14:21 UTC, joeribekker commented on src/sdg/api/serializers/producten.py
> +                if not product_versie_created:
else ;-)

2022-06-22 09:00 UTC, bart-maykin commented on src/sdg/api/serializers/producten.py
> +        if type(validated_data.get("catalogus")) is dict:
When you provide a catalog directly in a call then validated_data.get("catalogus") returns an object. If you don't then it returns a dict of the "lokale_overheid".

2022-07-13 06:32 UTC, joeribekker approved these changes

2022-07-13 06:32 UTC, merged