:sparkles: [#672] added doelgroep to the duplicate product choices
maykinmedia/sdg-invoervoorziening pull request #707
Opened 2022-07-27 11:04 UTC by bart-maykin

Fixes #672
_______

**Changes**

Added doelgroep to the product update page
added doelgroep to the duplicated product valt onder choices

2022-07-27 18:58 UTC, alextreme commented
Would require tests imho

2022-08-09 14:50 UTC, joeribekker requested changes

2022-08-09 14:50 UTC, joeribekker commented on src/sdg/producten/views/product.py
> +            "value": self.product.reference_product.most_recent_version.product.generiek_product.doelgroep,
```suggestion
            "value": self.product.generiek_product.doelgroep,
```

You are making a few unneccessery related lookups.

2022-08-10 10:28 UTC, joeribekker approved these changes

2022-08-10 10:28 UTC, merged