:sparkles: [#930] added validation on url fields to only allow https
maykinmedia/sdg-invoervoorziening pull request #937
Opened 2023-03-31 15:38 UTC by bart-maykin

Fixes #930

_______

**Changes**

- Added custom valiation for url fields to only allow https.
- Added data migration to change http to https in database.

2023-04-04 08:12 UTC, bart-maykin commented
Don't merge yet pr doesn't cover array link fields yet.

2023-04-06 11:07 UTC, joeribekker requested changes

2023-04-06 11:07 UTC, joeribekker commented on src/sdg/producten/models/validators.py
> +        raise ValidationError(_("Het url moet een geldige https adress zijn."))
```suggestion
        raise ValidationError(_("De URL moet beginnen met 'https://'. Let op de 's' achter 'http'."))
```

```suggestion
                    "reason": " ",
```

2023-04-12 13:15 UTC, joeribekker approved these changes

2023-04-12 13:15 UTC, merged